name: merriam_webster_dictionary_online
description: A client library to access the Merriam Webster Online API
version: 0.0.1
author: thinkdigital <jwhite@thinkdigital.software>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+2

dev_dependencies:
  pedantic: ^1.8.0+1
  test: ^1.9.2
  json_annotation: ^3.0.0
  json_serializable: ^3.2.3
